version: "3"
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=000000"
    restart: unless-stopped
    networks: 
      - "default"

networks:
  default:
